@if(__DEBUGMODE__ != 0)
	Debug.console.visible = true;
@endif

win.bringToFront();

global.game = new SceneManager(win);

var useNewGame = (System.getArgument("-newgame") !== void);

if (useNewGame)
{
	Debug.message(">>> -newgame detected, switching to ADV");
	game.setScene(SCENE_ADV);
	
	var adv = game.getScene(SCENE_ADV);
	if (adv !== void)
	{
		adv.start("00_z000", "");
	}
}
else
{
	game.changeScene(SCENE_TITLE);
}

delete boot;